"""Add link column to Hotel model with default value

Revision ID: 7ee2d00b0284
Revises: 79ed10498c1f
Create Date: 2024-12-01 03:54:32.337467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ee2d00b0284'
down_revision = '79ed10498c1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotel', sa.Column('link', sa.String(length=255), nullable=False, server_default='http://127.0.0.1:5000/add_hotel'))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotel', 'link')
    # ### end Alembic commands ###

    # ### end Alembic commands ###
